name: key-forge
services:
  key-forge-api:
    container_name: key-forge-api
    build: /src/backend/Host.
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
    volumes:
      - ./key-forge-api:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - /tmp/.dotnet/tools:/root/.dotnet/tools:ro

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: keyforge!1
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: